from __future__ import annotations
import argparse,json,re
from pathlib import Path
from urllib.parse import urljoin
import pandas as pd
import requests
from bs4 import BeautifulSoup
UA="Mozilla/5.0 (compatible; KeibaEVTool/0.4; respectful-low-rate-fetch)"
BASE="https://www.jra.go.jp/"
def links_from_homepage(session):
    r=session.get(BASE,headers={"User-Agent":UA},timeout=30); r.raise_for_status()
    soup=BeautifulSoup(r.text,"html.parser"); seen=set(); links=[]

    # Explicitly follow JRA's current syutsuba pages exposed from the homepage.
    for a in soup.select('a[href]'):
        href=urljoin(BASE,a.get("href",""))
        if href.endswith("/syutsuba.html") and "/keiba/race/" in href:
            try:
                pr=session.get(href,headers={"User-Agent":UA},timeout=30)
                if pr.ok:
                    ps=BeautifulSoup(pr.text,"html.parser")
                    for x in ps.select('a[href]'):
                        h=x.get("href","")
                        if "accessD.html?CNAME=" in h:
                            links.append({"url":urljoin(BASE,h),"text":x.get_text(" ",strip=True)})
                    for m in re.finditer(r'accessD\.html\?CNAME=([^\'"]+)',pr.text,flags=re.I):
                        u=urljoin(BASE,f"/JRADB/accessD.html?CNAME={m.group(1)}")
                        if u not in {z["url"] for z in links}: links.append({"url":u,"text":""})
            except Exception as e:
                print(f"WARN current syutsuba {href}: {e}")

    def add(href, text=""):
        href=urljoin(BASE,href)
        if "accessD.html?CNAME=" not in href or href in seen:
            return
        seen.add(href)
        links.append({"url":href,"text":text})

    # Directly probe the current week's public entry pages for the two Sunday feature pages.
    # JRA may expose these pages without linking them from the homepage navigation.
    for direct in ("/keiba/race/082/syutsuba.html","/keiba/race/083/syutsuba.html","/keiba/race/084/syutsuba.html","/keiba/race/085/syutsuba.html","/keiba/race/086/syutsuba.html","/keiba/race/087/syutsuba.html","/keiba/race/088/syutsuba.html","/keiba/race/089/syutsuba.html","/keiba/race/090/syutsuba.html","/keiba/race/091/syutsuba.html"):
        href=urljoin(BASE,direct)
        try:
            pr=session.get(href,headers={"User-Agent":UA},timeout=30)
            if pr.ok:
                ps=BeautifulSoup(pr.text,"html.parser")
                for link in ps.select('a[href]'):
                    h=link.get("href","")
                    if "accessD.html?CNAME=" in h:
                        links.append({"url":urljoin(BASE,h),"text":link.get_text(" ",strip=True)})
                for m in re.finditer(r'accessD\.html\?CNAME=([^\'"]+)',pr.text,flags=re.I):
                    u=urljoin(BASE,f"/JRADB/accessD.html?CNAME={m.group(1)}")
                    if u not in {z["url"] for z in links}: links.append({"url":u,"text":""})
        except Exception as e:
            print(f"WARN direct syutsuba {href}: {e}")

    # Ordinary links.
    for a in soup.select('a[href*="accessD.html?CNAME="]'):
        add(a.get("href",""), a.get_text(" ",strip=True))

    # Follow JRA's public "this week's races" / entry-table pages as a fallback.
    for a in soup.select('a[href]'):
        href=urljoin(BASE,a.get("href",""))
        if "/keiba/race/" in href and "syutsuba.html" in href:
            try:
                pr=session.get(href,headers={"User-Agent":UA},timeout=30)
                if pr.ok:
                    psoup=BeautifulSoup(pr.text,"html.parser")
                    for link in psoup.select('a[href]'):
                        h=link.get("href","")
                        if "accessD.html?CNAME=" in h:
                            add(h,link.get_text(" ",strip=True))
                    for m in re.finditer(r'accessD\.html\?CNAME=([^\'"]+)',pr.text,flags=re.I):
                        add(f"/JRADB/accessD.html?CNAME={m.group(1)}")
            except Exception as e:
                print(f"WARN syutsuba-page {href}: {e}")

    # Also follow JRA race/entry pages when the homepage does not expose accessD links directly.
    # These pages can contain the current accessD URLs after publication.
    page_links=[]
    for a in soup.select('a[href]'):
        href=urljoin(BASE,a.get("href",""))
        if "/keiba/race/" in href and ("syutsuba" in href or "accessD" in href):
            page_links.append(href)
    for page_url in dict.fromkeys(page_links):
        try:
            pr=session.get(page_url,headers={"User-Agent":UA},timeout=30)
            if pr.ok:
                psoup=BeautifulSoup(pr.text,"html.parser")
                for a in psoup.select('a[href*="accessD.html?CNAME="]'):
                    add(a.get("href",""), a.get_text(" ",strip=True))
                # Search page source as well because some JRA navigation is generated by script.
                for m in re.finditer(r'accessD\.html\?CNAME=([^\'"]+)', pr.text, flags=re.I):
                    add(f"/JRADB/accessD.html?CNAME={m.group(1)}")
        except Exception as e:
            print(f"WARN race-page {page_url}: {e}")

    # JRA also exposes current-race navigation through JavaScript actions.
    html=r.text
    patterns=[
        r'accessD\.html\?CNAME=([^\'"]+)',
        r'accessD\.html[^\n]{0,300}?[Cc][Nn][Aa][Mm][Ee]=([^\'"]+)',
        r'(?:doAction|do_action)\s*\(\s*[\'"](?:/)?JRADB/accessD\.html[\'"]\s*,\s*[\'"]([^\'"]+)[\'"]',
        r'(?:doAction|do_action)\s*\(\s*[\'"](?:accessD\.html)[\'"]\s*,\s*[\'"]([^\'"]+)[\'"]',
    ]
    for pat in patterns:
        for m in re.finditer(pat, html, flags=re.I):
            value=m.group(1)
            if value.startswith("http"):
                add(value)
            elif value.startswith("pw"):
                add(f"/JRADB/accessD.html?CNAME={value}")
            else:
                add(f"/JRADB/accessD.html?CNAME={value}")

    # Some pages put the action in data-* attributes or onclick handlers.
    for tag in soup.find_all(True):
        blob=" ".join(str(tag.get(k,"")) for k in ("onclick","data-action","data-url","data-href"))
        if "accessD.html" in blob:
            for m in re.finditer(r'(?:CNAME=)?(pw01dde[^\'";,)<>\s]+)', blob, flags=re.I):
                add(f"/JRADB/accessD.html?CNAME={m.group(1)}", tag.get_text(" ",strip=True))
    unique=[]
    seen_urls=set()
    for item in links:
        if item["url"] not in seen_urls:
            seen_urls.add(item["url"])
            unique.append(item)
    return unique
def parse_page(session,url):
    r=session.get(url,headers={"User-Agent":UA},timeout=30); r.raise_for_status()
    soup=BeautifulSoup(r.text,"html.parser"); page_text=soup.get_text(" ",strip=True)
    tables=pd.read_html(r.text); target=None
    for t in tables:
        cols=" ".join(str(c) for c in t.columns)
        if "馬名" in cols and "騎手" in cols: target=t; break
    if target is None: return None
    target=target.copy(); target.columns=[str(c) for c in target.columns]; out=[]
    for _,row in target.iterrows():
        vals={k:(None if pd.isna(v) else str(v)) for k,v in row.items()}
        if re.search(r"\d+"," ".join(v or "" for v in vals.values())): out.append(vals)
    meta={}
    m=re.search(r"(\d{4})年(\d+)月(\d+)日.*?(\d+)回(.+?)(\d+)日\s*(\d+)レース.*?コース：([\d,]+)メートル（(芝|ダート)",page_text)
    if m: meta={"race_date":f"{m.group(1)}-{int(m.group(2)):02d}-{int(m.group(3)):02d}","course":m.group(5),"meeting_no":m.group(4),"day_no":int(m.group(6)),"race_no":int(m.group(7)),"distance":int(m.group(8).replace(",","")),"surface":m.group(9)}
    return {"meta":meta,"rows":out}
def main(out):
    s=requests.Session(); links=links_from_homepage(s); races=[]
    for i,item in enumerate(links,1):
        try:
            parsed=parse_page(s,item["url"])
            if parsed: races.append({"url":item["url"],"label":item["text"],**parsed})
        except Exception as e: print(f"WARN {item['url']}: {e}")
        print(f"[{i}/{len(links)}]")
    out.parent.mkdir(parents=True,exist_ok=True); status="published" if races else "not_published_or_no_entries"; out.write_text(json.dumps({"source":BASE,"fetched_at":pd.Timestamp.now(tz="Asia/Tokyo").isoformat(),"status":status,"race_count":len(races),"row_count":sum(len(r.get("rows",[])) for r in races),"races":races},ensure_ascii=False,indent=2),encoding="utf-8"); print(f"status={status} races={len(races)} rows={sum(len(r.get("rows",[])) for r in races)}")
if __name__=="__main__":
    ap=argparse.ArgumentParser(); ap.add_argument("--out",default="data/processed/current_entries.json"); a=ap.parse_args(); main(Path(a.out))
